const lessonMeta = [
  { slug: 'a1-01-alfabeto', title: 'El Alfabeto', moduleId: 0 },
  { slug: 'a1-02-sustantivos', title: 'Los Sustantivos', moduleId: 0 },
  { slug: 'a1-03-adjetivos', title: 'Los Adjetivos', moduleId: 0 },
  { slug: 'a1-04-verbos', title: 'Verbos y Pronombres', moduleId: 0 },
  { slug: 'a1-05-adverbios', title: 'Los Adverbios', moduleId: 0 },
  { slug: 'a1-06-preguntas', title: 'Preguntas y Números', moduleId: 1 },
  { slug: 'a1-07-dialogando', title: 'Dialogando', moduleId: 1 },
  { slug: 'a1-08-mundo', title: 'El Español en el Mundo', moduleId: 1 },
  { slug: 'a1-09-saludos', title: 'Saludos y Despedidas', moduleId: 1 },
  { slug: 'a1-10-perfil', title: 'Mi Perfil Personal', moduleId: 1 },
  { slug: 'a1-11-rutina', title: 'Mi Rutina Diaria', moduleId: 2 },
  { slug: 'a1-12-presente', title: 'Más Allá de la Rutina', moduleId: 2 },
  { slug: 'a1-13-vives', title: '¿Dónde Vives?', moduleId: 2 },
  { slug: 'a1-14-tiempo', title: '¿Qué Tiempo Hace?', moduleId: 2 },
  { slug: 'a1-15-restaurante', title: 'En el Restaurante', moduleId: 2 },
  { slug: 'a1-16-practiquemos', title: 'Practiquemos', moduleId: 3 },
  { slug: 'a1-17-cocina', title: 'La Cocina Latinoamericana', moduleId: 3 },
  { slug: 'a1-18-comprar', title: '¡A Comprar!', moduleId: 3 },
  { slug: 'a1-19-telefono', title: 'Comunicación por Teléfono', moduleId: 3 },
  { slug: 'a1-20-planes', title: 'Haciendo Planes', moduleId: 3 },
  { slug: 'a1-21-imperativo', title: 'El Imperativo', moduleId: 4 },
  { slug: 'a1-22-presente-indicativo', title: 'Presente del Indicativo', moduleId: 4 },
  { slug: 'a1-23-gerundio', title: 'Estar + Gerundio', moduleId: 4 },
  { slug: 'a1-24-perfecto', title: 'Pretérito Perfecto', moduleId: 4 },
  { slug: 'a1-25-subjuntivo', title: 'Presente de Subjuntivo', moduleId: 4 },
  { slug: 'a1-26-cuatro-presentes', title: 'Los Cuatro Presentes', moduleId: 5 },
  { slug: 'a1-27-continuamos', title: 'Continuamos recorriendo', moduleId: 5 },
  { slug: 'a1-28-bariloche', title: 'Lectura: Bariloche', moduleId: 5 },
  { slug: 'a1-29-tito', title: 'Conversación con Tito', moduleId: 5 },
  { slug: 'a1-30-preparacion', title: 'Preparación para el Éxito', moduleId: 5 },
];

export const lessons = lessonMeta.map((meta, idx) => ({
  id: idx + 1,
  slug: meta.slug,
  title: meta.title,
  shortSummary: `Lección ${idx + 1}: ${meta.title}`,
  fullSummary: `Contenido completo de ${meta.title}.`,
  videoUrl: `https://www.youtube.com/embed/${idx + 1}`,
  slides: [
    { title: 'Concepto', content: 'Explicación principal.' },
    { title: 'Ejemplos', content: 'Frases de práctica.' },
    { title: 'Práctica', content: 'Actividad de revisión.' },
  ],
  resources: [{ name: `PDF ${meta.title}`, url: '#' }],
  quiz: {
    questions: [
      {
        question: `Pregunta clave - ${meta.title}`,
        options: ['Opción A', 'Opción B', 'Opción C'],
        correctAnswer: 'Opción A',
        correctFeedback: '¡Muy bien!',
        incorrectFeedback: 'Observa el ejemplo de contenido.',
      },
    ],
  },
  listeningExercise: {
    audioUrl: '#',
    questions: [{ question: 'Escucha y elige la respuesta correcta.', options: ['A', 'B', 'C'], correctAnswer: 'A' }],
  },
  isFree: idx < 5,
  moduleId: meta.moduleId,
  orderIndex: idx + 1,
}));
