CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR(10) NOT NULL,
    slug VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(200) NOT NULL,
    type VARCHAR(20) DEFAULT 'adult'
);

CREATE TABLE IF NOT EXISTS modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    order_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT REFERENCES modules(id) ON DELETE CASCADE,
    slug VARCHAR(100) UNIQUE NOT NULL,
    title VARCHAR(200) NOT NULL,
    short_summary TEXT,
    full_summary TEXT,
    video_url VARCHAR(500),
    order_index INTEGER NOT NULL,
    is_free BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
    title VARCHAR(200),
    content TEXT,
    order_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    url VARCHAR(500) NOT NULL,
    type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE UNIQUE
);

CREATE TABLE IF NOT EXISTS quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    correct_feedback TEXT,
    incorrect_feedback TEXT,
    order_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS quiz_options (
    question_id BIGINT REFERENCES quiz_questions(id) ON DELETE CASCADE,
    option_text VARCHAR(255) NOT NULL,
    PRIMARY KEY (question_id, option_text)
);

CREATE TABLE IF NOT EXISTS listening_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE UNIQUE,
    audio_url VARCHAR(500) NOT NULL,
    transcript TEXT
);

CREATE TABLE IF NOT EXISTS listening_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id BIGINT REFERENCES listening_exercises(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    correct_answer VARCHAR(255) NOT NULL,
    correct_feedback TEXT,
    incorrect_feedback TEXT,
    order_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS listening_options (
    question_id BIGINT REFERENCES listening_questions(id) ON DELETE CASCADE,
    option_text VARCHAR(255) NOT NULL,
    PRIMARY KEY (question_id, option_text)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500),
    current_course_id BIGINT REFERENCES courses(id),
    progress INTEGER DEFAULT 0,
    role VARCHAR(20) DEFAULT 'STUDENT',
    status VARCHAR(20) DEFAULT 'PENDING',
    email_verified BOOLEAN DEFAULT FALSE,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
    completed BOOLEAN DEFAULT FALSE,
    quiz_score INTEGER,
    completed_at TIMESTAMP,
    UNIQUE(user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS writing_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
    content TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    corrected BOOLEAN DEFAULT FALSE,
    feedback TEXT,
    score INTEGER
);

CREATE TABLE IF NOT EXISTS evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    module_number INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    passing_score INTEGER DEFAULT 70
);

CREATE TABLE IF NOT EXISTS user_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    evaluation_id BIGINT REFERENCES evaluations(id) ON DELETE CASCADE,
    score INTEGER,
    passed BOOLEAN,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    image_url VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_lessons_module ON lessons(module_id);
CREATE INDEX IF NOT EXISTS idx_lessons_slug ON lessons(slug);
CREATE INDEX IF NOT EXISTS idx_user_progress_user ON user_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_user_progress_lesson ON user_progress(lesson_id);
CREATE INDEX IF NOT EXISTS idx_writing_submissions_user ON writing_submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role_status ON users(role, status);
